import turtle
turtle.setup(650,350,200,200)
#控制大脸在屏幕中间
turtle.penup()
turtle.right(90)
turtle.fd(20)
turtle.pendown()
#画出大脸
turtle.pensize(160)
turtle.pencolor("yellow")
turtle.circle(50)
turtle.pencolor("red")
#准备画眼睛
turtle.left(180)
turtle.penup()
turtle.fd(50)
turtle.pendown()
turtle.seth(0)
turtle.pensize(1)
#左眼
turtle.penup()
turtle.fd(-48)
turtle.seth(40)
turtle.pendown()
turtle.circle(-70,80)
#右眼
turtle.penup()
turtle.seth(0)
turtle.fd(27)
turtle.seth(40)
turtle.pendown()
turtle.circle(-70,80)
#嘴巴
turtle.penup()
turtle.seth(0)
turtle.fd(-155)
turtle.seth(-90)
turtle.fd(110)
turtle.seth(-40)
turtle.pendown()
turtle.circle(80,80)

turtle.done()
